version: '3.7'

services:
  logger-rpcap:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: 'always'
    container_name: logger-rpcap
    # volumes:
    #   - ./config.yml:/app/config.yml
    #   - '~/Documents/Lost Ark Logs:/mnt/raid1/apps/Lost Ark Logs'