name: Build App
 
on:
  push:
    tags:
      - '*'
  
  # manually trigger the workflow
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      - run: dotnet restore
        # Create linux binaries
      - run: dotnet publish -c Release -o out/linux --os linux
        # Create windows binaries
      - run: dotnet publish -c Release -o out/win --os win
      - run: cp bin/*.so out/linux
      - run: cp bin/*.dll out/win
      - uses: actions/upload-artifact@v3
        with:
          name: dps-meter-win
          path: out/win
      - uses: actions/upload-artifact@v3
        with:
          name: dps-meter-linux
          path: out/linux
      - uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true